#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# this script will be sourced from the components deployment
#


COMP_INTERFACE_FILES="
$SMART_ROOT_ACE/lib/libDefaultCoordinationService.so
"
 
BEHAVIOR_UTILITY_FILES="
src-gen/system/CoordinationModuleConnections.json
"
 
COMP_INTERFACE_FILES_MISSING=false
for FILE in $COMP_INTERFACE_FILES; do
	if [ ! -e $FILE ]; then
		echo "Deployment: No such file or directory: $FILE"
		COMP_INTERFACE_FILES_MISSING=true
	fi
done

if [ "$COMP_INTERFACE_FILES_MISSING" = "true" ]; then
	echo	
	echo "ERROR: FILES ARE MISSING FROM THE DEPLOYMENT (see above). Did you compile all components interfaces/components?"
	echo 
	exit 1
fi

echo "Sourcing behaviorProjectFiles"
source src-gen/system/behaviorProjectFiles.sh 2>&1

BEHAVIOR_PROJECT_MODEL_FILES=""
shopt -u | grep -q nullglob && changed=true && shopt -s nullglob
for DIR in "${BEHAVIOR_PROJECTS_PATH[@]}"; do
	echo "Behavior files for $DIR"
	for entry in "$DIR"/model/*.smartTcl
	do
		echo "Behavior file: $entry"
  		BEHAVIOR_PROJECT_MODEL_FILES="$BEHAVIOR_PROJECT_MODEL_FILES $entry"
	done
done
[ $changed ] && shopt -u nullglob; unset changed



cp -rv $BEHAVIOR_PROJECT_MODEL_FILES $TMPDIR/behaviorFiles 2>&1
cp -rv $COMP_INTERFACE_FILES $TMPDIR/behaviorFiles 2>&1
cp -rv $BEHAVIOR_UTILITY_FILES $TMPDIR/behaviorFiles 2>&1
