//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _LASERTASK_HH
#define _LASERTASK_HH

#include "LaserTaskCore.hh"

#include <webots/Robot.hpp>
#include <webots/Lidar.hpp>

// TODO: Try to get it from the world if possible
// This parameter has to be the same in the ComponentWebotsSimulator
#define TIME_STEP 64

// Modifies these parameters according to the sensor used
#define FOV 80.0 // in meter
#define RES 180  // in degree
#define UNIT_FACTOR 100.0 // By default, it is in 0.01 unit
#define MEASURE_UNIT 1.0 // From the sensor (1.0 for meter, 0.001 for mm)

class LaserTask  : public LaserTaskCore
{
private:
	webots::Robot *wb_robot;
	webots::Lidar *wb_lidar;

	// TODO: Verify if it should be private or public
	//static uint scan_count;

	CommBasicObjects::CommMobileLaserScan scan;

public:
	unsigned long scan_count;
	LaserTask(SmartACE::SmartComponent *comp);
	virtual ~LaserTask();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
