//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _PARAMUPDATEHANDLER_HH_
#define _PARAMUPDATEHANDLER_HH_

#include "aceSmartSoft.hh"
#include "ParameterStateStruct.hh"

class ParamUpdateHandler: public SmartACE::ParameterUpdateHandler {
public:
	SmartACE::CommParameterResponse handleParameter(const SmartACE::CommParameterRequest& request);

	ParameterStateStruct getGlobalState() const;
	
	void loadParameter(SmartACE::SmartIniParameter &parameter);

protected:
	//local globale state stuff
	ParameterStateStruct globalState,commitState;
	mutable SmartACE::SmartMutex globalStateLock;
};

#endif
