//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPUTINGTASK_HH
#define _COMPUTINGTASK_HH

#include "ComputingTaskCore.hh"

class ComputingTask  : public ComputingTaskCore
{

private:
	int updateCounter = 0;
	double velocity = 0.0; // in m/s
	double turnrate = 0.0; // in rad/s
	CommBasicObjects::CommMobileLaserScan laserScan;

	virtual void on_LaserServiceIn(const CommBasicObjects::CommMobileLaserScan &input);

public:
	ComputingTask(SmartACE::SmartComponent *comp);
	virtual ~ComputingTask();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
