#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# This script collects the generated ini-file parts and combines them into single ini-files (one for each component artefact)
#

# create subfolder combined-ini-files (if not yet created)
echo "create subfolder src-gen/combined-ini-files"
mkdir -p src-gen/combined-ini-files

# clean-up old combined-ini-files before they are generated again
echo "clean-up src-gen/combined-ini-files subfolder"
rm src-gen/combined-ini-files/*.ini

# create ini-file ComponentLaserObstacleAvoidTest.ini
echo "create ini-file ComponentLaserObstacleAvoidTest.ini"
cp src-gen/system/ComponentLaserObstacleAvoidTest.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentLaserObstacleAvoidTest.ini ]; then
  cat src-gen/params/ComponentLaserObstacleAvoidTest.ini >> src-gen/combined-ini-files/ComponentLaserObstacleAvoidTest.ini
fi

# create ini-file ComponentWebots.ini
echo "create ini-file ComponentWebots.ini"
cp src-gen/system/ComponentWebots.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentWebots.ini ]; then
  cat src-gen/params/ComponentWebots.ini >> src-gen/combined-ini-files/ComponentWebots.ini
fi

# create ini-file ComponentWebotsLidarTest.ini
echo "create ini-file ComponentWebotsLidarTest.ini"
cp src-gen/system/ComponentWebotsLidarTest.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentWebotsLidarTest.ini ]; then
  cat src-gen/params/ComponentWebotsLidarTest.ini >> src-gen/combined-ini-files/ComponentWebotsLidarTest.ini
fi

# create ini-file ComponentWebotsRobotino3.ini
echo "create ini-file ComponentWebotsRobotino3.ini"
cp src-gen/system/ComponentWebotsRobotino3.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentWebotsRobotino3.ini ]; then
  cat src-gen/params/ComponentWebotsRobotino3.ini >> src-gen/combined-ini-files/ComponentWebotsRobotino3.ini
fi

