//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _WEBOTSCONTROLLERTASK_HH
#define _WEBOTSCONTROLLERTASK_HH

#include "WebotsControllerTaskCore.hh"

#include <webots/Motor.hpp>
#include <webots/Robot.hpp>
#include <webots/Lidar.hpp>

#define OMEGA_ADJUST 0
#define MAX_SPEED 2.5
#define TIME_STEP 64

class WebotsControllerTask  : public WebotsControllerTaskCore
{

private:
	webots::Robot *robot;
	webots::Motor *rightMotor;
	webots::Motor *leftMotor;
	webots::Lidar *lidar;


public:
	WebotsControllerTask(SmartACE::SmartComponent *comp);
	virtual ~WebotsControllerTask();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
