//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _WEBOTSCONTROLLERTASK_HH
#define _WEBOTSCONTROLLERTASK_HH

#include "WebotsControllerTaskCore.hh"

#include <webots/Motor.hpp>
#include <webots/Robot.hpp>


// These parameters have to be consistent with the robot used
#define WHEEL_GAP 0.269     // in meter
#define WHEEL_RADIUS 0.0975 // in meter
#define MAX_SPEED 12.3      // in rad/s


class WebotsControllerTask  : public WebotsControllerTaskCore
{

private:
	int wb_time_step;
	webots::Robot *wb_robot;
	webots::Motor *wb_right_motor;
	webots::Motor *wb_left_motor;


public:
	WebotsControllerTask(SmartACE::SmartComponent *comp);
	virtual ~WebotsControllerTask();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
