//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENTWEBOTSROBOTINO3CORE_HH
#define _COMPONENTWEBOTSROBOTINO3CORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>

class ComponentWebotsRobotino3Core
{
private:

public:
	ComponentWebotsRobotino3Core();
	SmartACE::SmartMutex Robotino3Mutex;
	double vel_X; // in m/s
	double vel_Y; // in m/s
	double vel_W; // in rad/s
};
	
#endif
