//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _ROBOTINO3TASK_HH
#define _ROBOTINO3TASK_HH

#include "Robotino3TaskCore.hh"

#include <webots/Motor.hpp>
#include <webots/Robot.hpp>


// Robotino 3 specification
#define WHEEL_GAP    0.184  // in meter
#define WHEEL_RADIUS 0.0625 // in meter


class Robotino3Task  : public Robotino3TaskCore
{

private:
	int wb_time_step;
	double motor_max_speed; // in rad/s
	webots::Robot *wb_robot;
	webots::Motor *wb_motor_0;
	webots::Motor *wb_motor_1;
	webots::Motor *wb_motor_2;


public:
	Robotino3Task(SmartACE::SmartComponent *comp);
	virtual ~Robotino3Task();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
