//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _BATTERYEVENTSERVICEOUT_EVENT_TEST_HANDLER_CORE_HH
#define _BATTERYEVENTSERVICEOUT_EVENT_TEST_HANDLER_CORE_HH
		
#include "aceSmartSoft.hh"

#include <CommBasicObjects/CommBatteryEvent.hh>
#include <CommBasicObjects/CommBatteryParameter.hh>
#include <CommBasicObjects/CommBatteryState.hh>

class BatteryEventServiceOutEventTestHandlerCore : public SmartACE::EventTestHandler<CommBasicObjects::CommBatteryParameter, CommBasicObjects::CommBatteryEvent, CommBasicObjects::CommBatteryState>
{
};
#endif
