//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "NavigationVelocityServiceInUpcallManager.hh"

NavigationVelocityServiceInUpcallManager::NavigationVelocityServiceInUpcallManager(
	Smart::InputSubject<CommBasicObjects::CommNavigationVelocity> *subject,
	const int &prescaleFactor)
	:	Smart::IInputHandler<CommBasicObjects::CommNavigationVelocity>(subject, prescaleFactor)
{  }
NavigationVelocityServiceInUpcallManager::~NavigationVelocityServiceInUpcallManager()
{  }

void NavigationVelocityServiceInUpcallManager::notify_upcalls(const CommBasicObjects::CommNavigationVelocity &input)
{
	for(auto it=upcalls.begin(); it!=upcalls.end(); it++) {
		(*it)->on_NavigationVelocityServiceIn(input);
	}
}

void NavigationVelocityServiceInUpcallManager::attach(NavigationVelocityServiceInUpcallInterface *upcall)
{
	upcalls.push_back(upcall);
}
void NavigationVelocityServiceInUpcallManager::detach(NavigationVelocityServiceInUpcallInterface *upcall)
{
	upcalls.remove(upcall);
}
