//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _PIONEERTASK_HH
#define _PIONEERTASK_HH

#include "PioneerTaskCore.hh"

#include <webots/Motor.hpp>
#include <webots/Robot.hpp>
#include <webots/Lidar.hpp>

// TODO: MODIFIER
// These 4 parameters have to be the same in the ComponentWebotsSimulator
#define MAX_LIDAR_DIST 80.0 // in meter
#define WHEEL_GAP 0.269     // in meter
#define WHEEL_RADIUS 0.0975 // in meter
#define MAX_SPEED 12.3      // in rad/s

// TODO: RENDRE GENERIC
// This parameter has to be the same in the ComponentWebotsLidar
#define TIME_STEP 64

class PioneerTask  : public PioneerTaskCore
{

private:
	// TODO: ADAPTER
	webots::Robot *wb_robot;
	webots::Motor *wb_right_motor;
	webots::Motor *wb_left_motor;
	webots::Lidar *wb_lidar;

public:
	PioneerTask(SmartACE::SmartComponent *comp);
	virtual ~PioneerTask();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
