//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ComponentWebotsRobotino3.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ComponentWebotsRobotino3AcePortFactory.hh"

#include "BatteryEventServiceOutEventTestHandler.hh"

// initialize static singleton pointer to zero
ComponentWebotsRobotino3* ComponentWebotsRobotino3::_componentWebotsRobotino3 = 0;

// constructor
ComponentWebotsRobotino3::ComponentWebotsRobotino3()
{
	std::cout << "constructor of ComponentWebotsRobotino3\n";
	
	// set all pointer members to NULL
	baseStateAnswerer = NULL;
	baseStateAnswererInputTaskTrigger = NULL;
	baseStateQueryHandler = NULL;
	baseStateServiceOut = NULL;
	batteryEventServiceOut = NULL;
	batteryEventServiceOutEventTestHandler = nullptr; 
	batteryEventTask = NULL;
	batteryEventTaskTrigger = NULL;
	//componentWebotsRobotino3Params = NULL;
	//coordinationPort = NULL;
	localizationUpdateHandler = NULL;
	localizationUpdateServiceIn = NULL;
	localizationUpdateServiceInInputTaskTrigger = NULL;
	localizationUpdateServiceInUpcallManager = NULL;
	navigationVelocityHandler = NULL;
	navigationVelocityServiceIn = NULL;
	navigationVelocityServiceInInputTaskTrigger = NULL;
	navigationVelocityServiceInUpcallManager = NULL;
	robotino3Task = NULL;
	robotino3TaskTrigger = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	param = NULL;
	
	// set default ini parameter values
	connections.component.name = "ComponentWebotsRobotino3";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.baseStateAnswerer.serviceName = "BaseStateAnswerer";
	connections.baseStateAnswerer.roboticMiddleware = "ACE_SmartSoft";
	connections.baseStateServiceOut.serviceName = "BaseStateServiceOut";
	connections.baseStateServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.batteryEventServiceOut.serviceName = "BatteryEventServiceOut";
	connections.batteryEventServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.localizationUpdateServiceIn.serviceName = "LocalizationUpdateServiceIn";
	connections.localizationUpdateServiceIn.roboticMiddleware = "ACE_SmartSoft";
	connections.navigationVelocityServiceIn.serviceName = "NavigationVelocityServiceIn";
	connections.navigationVelocityServiceIn.roboticMiddleware = "ACE_SmartSoft";
	connections.batteryEventTask.minActFreq = 0.0;
	connections.batteryEventTask.maxActFreq = 0.0;
	// scheduling default parameters
	connections.batteryEventTask.scheduler = "DEFAULT";
	connections.batteryEventTask.priority = -1;
	connections.batteryEventTask.cpuAffinity = -1;
	connections.robotino3Task.minActFreq = 0.0;
	connections.robotino3Task.maxActFreq = 0.0;
	// scheduling default parameters
	connections.robotino3Task.scheduler = "DEFAULT";
	connections.robotino3Task.priority = -1;
	connections.robotino3Task.cpuAffinity = -1;
	connections.localizationUpdateHandler.prescale = 1;
	connections.navigationVelocityHandler.prescale = 1;
	
	// initialize members of ComponentWebotsRobotino3ROSExtension
	
	// initialize members of OpcUaBackendComponentGeneratorExtension
	
	// initialize members of PlainOpcUaComponentWebotsRobotino3Extension
	
}

void ComponentWebotsRobotino3::addPortFactory(const std::string &name, ComponentWebotsRobotino3PortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ComponentWebotsRobotino3::addExtension(ComponentWebotsRobotino3Extension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ComponentWebotsRobotino3::getComponentImpl()
{
	return dynamic_cast<ComponentWebotsRobotino3AcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ComponentWebotsRobotino3::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}




/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ComponentWebotsRobotino3::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ComponentWebotsRobotino3::startAllTasks() {
	// start task BatteryEventTask
	if(connections.batteryEventTask.scheduler != "DEFAULT") {
		ACE_Sched_Params batteryEventTask_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.batteryEventTask.scheduler == "FIFO") {
			batteryEventTask_SchedParams.policy(ACE_SCHED_FIFO);
			batteryEventTask_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.batteryEventTask.scheduler == "RR") {
			batteryEventTask_SchedParams.policy(ACE_SCHED_RR);
			batteryEventTask_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		batteryEventTask->start(batteryEventTask_SchedParams, connections.batteryEventTask.cpuAffinity);
	} else {
		batteryEventTask->start();
	}
	// start task Robotino3Task
	if(connections.robotino3Task.scheduler != "DEFAULT") {
		ACE_Sched_Params robotino3Task_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.robotino3Task.scheduler == "FIFO") {
			robotino3Task_SchedParams.policy(ACE_SCHED_FIFO);
			robotino3Task_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.robotino3Task.scheduler == "RR") {
			robotino3Task_SchedParams.policy(ACE_SCHED_RR);
			robotino3Task_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		robotino3Task->start(robotino3Task_SchedParams, connections.robotino3Task.cpuAffinity);
	} else {
		robotino3Task->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ComponentWebotsRobotino3::startAllTimers() {
}


Smart::TaskTriggerSubject* ComponentWebotsRobotino3::getInputTaskTriggerFromString(const std::string &client)
{
	if(client == "LocalizationUpdateServiceIn") return localizationUpdateServiceInInputTaskTrigger;
	if(client == "NavigationVelocityServiceIn") return navigationVelocityServiceInInputTaskTrigger;
	
	return NULL;
}


void ComponentWebotsRobotino3::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		// print out the actual parameters which are used to initialize the component
		std::cout << " \nComponentDefinition Initial-Parameters:\n" << COMP->getParameters() << std::endl;
		
		// initializations of ComponentWebotsRobotino3ROSExtension
		
		// initializations of OpcUaBackendComponentGeneratorExtension
		
		// initializations of PlainOpcUaComponentWebotsRobotino3Extension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ComponentWebotsRobotino3PortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ComponentWebotsRobotino3AcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ComponentWebotsRobotino3 is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		batteryEventServiceOutEventTestHandler = std::make_shared<BatteryEventServiceOutEventTestHandler>();
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		baseStateAnswerer = portFactoryRegistry[connections.baseStateAnswerer.roboticMiddleware]->createBaseStateAnswerer(connections.baseStateAnswerer.serviceName);
		baseStateAnswererInputTaskTrigger = new Smart::QueryServerTaskTrigger<CommBasicObjects::CommVoid, CommBasicObjects::CommBaseState>(baseStateAnswerer);
		baseStateServiceOut = portFactoryRegistry[connections.baseStateServiceOut.roboticMiddleware]->createBaseStateServiceOut(connections.baseStateServiceOut.serviceName);
		batteryEventServiceOutEventTestHandler = std::make_shared<BatteryEventServiceOutEventTestHandler>();
		batteryEventServiceOut = portFactoryRegistry[connections.batteryEventServiceOut.roboticMiddleware]->createBatteryEventServiceOut(connections.batteryEventServiceOut.serviceName, batteryEventServiceOutEventTestHandler);
		localizationUpdateServiceIn = portFactoryRegistry[connections.localizationUpdateServiceIn.roboticMiddleware]->createLocalizationUpdateServiceIn(connections.localizationUpdateServiceIn.serviceName);
		navigationVelocityServiceIn = portFactoryRegistry[connections.navigationVelocityServiceIn.roboticMiddleware]->createNavigationVelocityServiceIn(connections.navigationVelocityServiceIn.serviceName);
		
		// create client ports
		
		// create InputTaskTriggers and UpcallManagers
		localizationUpdateServiceInInputTaskTrigger = new Smart::InputTaskTrigger<CommBasicObjects::CommBasePositionUpdate>(localizationUpdateServiceIn);
		localizationUpdateServiceInUpcallManager = new LocalizationUpdateServiceInUpcallManager(localizationUpdateServiceIn);
		navigationVelocityServiceInInputTaskTrigger = new Smart::InputTaskTrigger<CommBasicObjects::CommNavigationVelocity>(navigationVelocityServiceIn);
		navigationVelocityServiceInUpcallManager = new NavigationVelocityServiceInUpcallManager(navigationVelocityServiceIn);
		
		// create input-handler
		localizationUpdateHandler = new LocalizationUpdateHandler(localizationUpdateServiceIn, connections.localizationUpdateHandler.prescale);
		navigationVelocityHandler = new NavigationVelocityHandler(navigationVelocityServiceIn, connections.navigationVelocityHandler.prescale);
		
		// create request-handlers
		baseStateQueryHandler = new BaseStateQueryHandler(baseStateAnswerer);
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		
		// create parameter slave
		param = new SmartACE::ParameterSlave(component, &paramHandler);
		
		
		// create Task BatteryEventTask
		batteryEventTask = new BatteryEventTask(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.batteryEventTask.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.batteryEventTask.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(batteryEventTask);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				batteryEventTaskTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task BatteryEventTask" << std::endl;
			}
		} else if(connections.batteryEventTask.trigger == "DataTriggered") {
			batteryEventTaskTrigger = getInputTaskTriggerFromString(connections.batteryEventTask.inPortRef);
			if(batteryEventTaskTrigger != NULL) {
				batteryEventTaskTrigger->attach(batteryEventTask, connections.batteryEventTask.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.batteryEventTask.inPortRef << " as activation source for Task BatteryEventTask" << std::endl;
			}
		} 
		
		// create Task Robotino3Task
		robotino3Task = new Robotino3Task(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.robotino3Task.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.robotino3Task.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(robotino3Task);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				robotino3TaskTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task Robotino3Task" << std::endl;
			}
		} else if(connections.robotino3Task.trigger == "DataTriggered") {
			robotino3TaskTrigger = getInputTaskTriggerFromString(connections.robotino3Task.inPortRef);
			if(robotino3TaskTrigger != NULL) {
				robotino3TaskTrigger->attach(robotino3Task, connections.robotino3Task.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.robotino3Task.inPortRef << " as activation source for Task Robotino3Task" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ComponentWebotsRobotino3::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ComponentWebotsRobotino3::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(batteryEventTaskTrigger != NULL){
		batteryEventTaskTrigger->detach(batteryEventTask);
		delete batteryEventTask;
	}
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(robotino3TaskTrigger != NULL){
		robotino3TaskTrigger->detach(robotino3Task);
		delete robotino3Task;
	}

	// destroy all input-handler
	delete localizationUpdateHandler;
	delete navigationVelocityHandler;

	// destroy InputTaskTriggers and UpcallManagers
	delete localizationUpdateServiceInInputTaskTrigger;
	delete localizationUpdateServiceInUpcallManager;
	delete navigationVelocityServiceInInputTaskTrigger;
	delete navigationVelocityServiceInUpcallManager;

	// destroy client ports

	// destroy server ports
	delete baseStateAnswerer;
	delete baseStateAnswererInputTaskTrigger;
	delete baseStateServiceOut;
	delete batteryEventServiceOut;
	delete localizationUpdateServiceIn;
	delete navigationVelocityServiceIn;
	// destroy event-test handlers (if needed)
	batteryEventServiceOutEventTestHandler;
	
	// destroy request-handlers
	delete baseStateQueryHandler;
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	delete param;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of ComponentWebotsRobotino3ROSExtension
	
	// destruction of OpcUaBackendComponentGeneratorExtension
	
	// destruction of PlainOpcUaComponentWebotsRobotino3Extension
	
}

void ComponentWebotsRobotino3::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ComponentWebotsRobotino3.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ComponentWebotsRobotino3.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ComponentWebotsRobotino3.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		
		// load parameters for server BaseStateAnswerer
		parameter.getString("BaseStateAnswerer", "serviceName", connections.baseStateAnswerer.serviceName);
		if(parameter.checkIfParameterExists("BaseStateAnswerer", "roboticMiddleware")) {
			parameter.getString("BaseStateAnswerer", "roboticMiddleware", connections.baseStateAnswerer.roboticMiddleware);
		}
		// load parameters for server BaseStateServiceOut
		parameter.getString("BaseStateServiceOut", "serviceName", connections.baseStateServiceOut.serviceName);
		if(parameter.checkIfParameterExists("BaseStateServiceOut", "roboticMiddleware")) {
			parameter.getString("BaseStateServiceOut", "roboticMiddleware", connections.baseStateServiceOut.roboticMiddleware);
		}
		// load parameters for server BatteryEventServiceOut
		parameter.getString("BatteryEventServiceOut", "serviceName", connections.batteryEventServiceOut.serviceName);
		if(parameter.checkIfParameterExists("BatteryEventServiceOut", "roboticMiddleware")) {
			parameter.getString("BatteryEventServiceOut", "roboticMiddleware", connections.batteryEventServiceOut.roboticMiddleware);
		}
		// load parameters for server LocalizationUpdateServiceIn
		parameter.getString("LocalizationUpdateServiceIn", "serviceName", connections.localizationUpdateServiceIn.serviceName);
		if(parameter.checkIfParameterExists("LocalizationUpdateServiceIn", "roboticMiddleware")) {
			parameter.getString("LocalizationUpdateServiceIn", "roboticMiddleware", connections.localizationUpdateServiceIn.roboticMiddleware);
		}
		// load parameters for server NavigationVelocityServiceIn
		parameter.getString("NavigationVelocityServiceIn", "serviceName", connections.navigationVelocityServiceIn.serviceName);
		if(parameter.checkIfParameterExists("NavigationVelocityServiceIn", "roboticMiddleware")) {
			parameter.getString("NavigationVelocityServiceIn", "roboticMiddleware", connections.navigationVelocityServiceIn.roboticMiddleware);
		}
		
		// load parameters for task BatteryEventTask
		parameter.getDouble("BatteryEventTask", "minActFreqHz", connections.batteryEventTask.minActFreq);
		parameter.getDouble("BatteryEventTask", "maxActFreqHz", connections.batteryEventTask.maxActFreq);
		parameter.getString("BatteryEventTask", "triggerType", connections.batteryEventTask.trigger);
		if(connections.batteryEventTask.trigger == "PeriodicTimer") {
			parameter.getDouble("BatteryEventTask", "periodicActFreqHz", connections.batteryEventTask.periodicActFreq);
		} else if(connections.batteryEventTask.trigger == "DataTriggered") {
			parameter.getString("BatteryEventTask", "inPortRef", connections.batteryEventTask.inPortRef);
			parameter.getInteger("BatteryEventTask", "prescale", connections.batteryEventTask.prescale);
		}
		if(parameter.checkIfParameterExists("BatteryEventTask", "scheduler")) {
			parameter.getString("BatteryEventTask", "scheduler", connections.batteryEventTask.scheduler);
		}
		if(parameter.checkIfParameterExists("BatteryEventTask", "priority")) {
			parameter.getInteger("BatteryEventTask", "priority", connections.batteryEventTask.priority);
		}
		if(parameter.checkIfParameterExists("BatteryEventTask", "cpuAffinity")) {
			parameter.getInteger("BatteryEventTask", "cpuAffinity", connections.batteryEventTask.cpuAffinity);
		}
		// load parameters for task Robotino3Task
		parameter.getDouble("Robotino3Task", "minActFreqHz", connections.robotino3Task.minActFreq);
		parameter.getDouble("Robotino3Task", "maxActFreqHz", connections.robotino3Task.maxActFreq);
		parameter.getString("Robotino3Task", "triggerType", connections.robotino3Task.trigger);
		if(connections.robotino3Task.trigger == "PeriodicTimer") {
			parameter.getDouble("Robotino3Task", "periodicActFreqHz", connections.robotino3Task.periodicActFreq);
		} else if(connections.robotino3Task.trigger == "DataTriggered") {
			parameter.getString("Robotino3Task", "inPortRef", connections.robotino3Task.inPortRef);
			parameter.getInteger("Robotino3Task", "prescale", connections.robotino3Task.prescale);
		}
		if(parameter.checkIfParameterExists("Robotino3Task", "scheduler")) {
			parameter.getString("Robotino3Task", "scheduler", connections.robotino3Task.scheduler);
		}
		if(parameter.checkIfParameterExists("Robotino3Task", "priority")) {
			parameter.getInteger("Robotino3Task", "priority", connections.robotino3Task.priority);
		}
		if(parameter.checkIfParameterExists("Robotino3Task", "cpuAffinity")) {
			parameter.getInteger("Robotino3Task", "cpuAffinity", connections.robotino3Task.cpuAffinity);
		}
		if(parameter.checkIfParameterExists("LocalizationUpdateHandler", "prescale")) {
			parameter.getInteger("LocalizationUpdateHandler", "prescale", connections.localizationUpdateHandler.prescale);
		}
		if(parameter.checkIfParameterExists("NavigationVelocityHandler", "prescale")) {
			parameter.getInteger("NavigationVelocityHandler", "prescale", connections.navigationVelocityHandler.prescale);
		}
		
		// load parameters for ComponentWebotsRobotino3ROSExtension
		
		// load parameters for OpcUaBackendComponentGeneratorExtension
		
		// load parameters for PlainOpcUaComponentWebotsRobotino3Extension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
		paramHandler.loadParameter(parameter);
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
