//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _LOCALIZATIONUPDATESERVICEIN_UPCALL_MANAGER_HH
#define _LOCALIZATIONUPDATESERVICEIN_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "LocalizationUpdateServiceInUpcallInterface.hh"

/** LocalizationUpdateServiceInUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort LocalizationUpdateServiceIn and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class LocalizationUpdateServiceInUpcallManager
:	public Smart::IInputHandler<CommBasicObjects::CommBasePositionUpdate>
{
private:
	// list of associated updalls
	std::list<LocalizationUpdateServiceInUpcallInterface*> upcalls;

	// call the on_LocalizationUpdateServiceIn of all the attached LocalizationUpdateServiceInUpcallInterfaces
	void notify_upcalls(const CommBasicObjects::CommBasePositionUpdate &input);
	
protected:
	virtual void handle_input(const CommBasicObjects::CommBasePositionUpdate &input) {
		// relay input-handling to all attached LocalizationUpdateServiceInUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	LocalizationUpdateServiceInUpcallManager(
		Smart::InputSubject<CommBasicObjects::CommBasePositionUpdate> *subject,
		const int &prescaleFactor=1
	);
	virtual ~LocalizationUpdateServiceInUpcallManager();
	
	void attach(LocalizationUpdateServiceInUpcallInterface *upcall);
	void detach(LocalizationUpdateServiceInUpcallInterface *upcall);
};

#endif
