//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "LocalizationUpdateServiceInUpcallManager.hh"

LocalizationUpdateServiceInUpcallManager::LocalizationUpdateServiceInUpcallManager(
	Smart::InputSubject<CommBasicObjects::CommBasePositionUpdate> *subject,
	const int &prescaleFactor)
	:	Smart::IInputHandler<CommBasicObjects::CommBasePositionUpdate>(subject, prescaleFactor)
{  }
LocalizationUpdateServiceInUpcallManager::~LocalizationUpdateServiceInUpcallManager()
{  }

void LocalizationUpdateServiceInUpcallManager::notify_upcalls(const CommBasicObjects::CommBasePositionUpdate &input)
{
	for(auto it=upcalls.begin(); it!=upcalls.end(); it++) {
		(*it)->on_LocalizationUpdateServiceIn(input);
	}
}

void LocalizationUpdateServiceInUpcallManager::attach(LocalizationUpdateServiceInUpcallInterface *upcall)
{
	upcalls.push_back(upcall);
}
void LocalizationUpdateServiceInUpcallManager::detach(LocalizationUpdateServiceInUpcallInterface *upcall)
{
	upcalls.remove(upcall);
}
