//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _NAVIGATIONVELOCITYHANDLER_CORE_HH
#define _NAVIGATIONVELOCITYHANDLER_CORE_HH

#include <aceSmartSoft.hh>

// include the main input-handler interface
#include "NavigationVelocityServiceInUpcallInterface.hh"
// include all other input interfaces (if any)

// include all interaction-observer interfaces
#include <NavigationVelocityHandlerObserverInterface.hh>

class NavigationVelocityHandlerCore
:	public Smart::InputTaskTrigger<CommBasicObjects::CommNavigationVelocity>
,	public NavigationVelocityServiceInUpcallInterface
{
private:
	Smart::StatusCode updateStatus;
	CommBasicObjects::CommNavigationVelocity lastUpdate;
	
	
	virtual void updateAllCommObjects();
	
	// internal input handling method
	virtual void handle_input(const CommBasicObjects::CommNavigationVelocity& input) {
		this->updateAllCommObjects();
		// call the input handler method (which has to be implemented in derived classes)
		this->on_NavigationVelocityServiceIn(input);
		// notify all attached interaction observers
		this->notify_all_interaction_observers();
		// call implementation of base class
		Smart::InputTaskTrigger<CommBasicObjects::CommNavigationVelocity>::handle_input(input);
	}
	
/**
 * Implementation of the Subject part of an InteractionObserver
 */
private:
	std::mutex interaction_observers_mutex;
	std::list<NavigationVelocityHandlerObserverInterface*> interaction_observers;
protected:
	void notify_all_interaction_observers();
public:
	void attach_interaction_observer(NavigationVelocityHandlerObserverInterface *observer);
	void detach_interaction_observer(NavigationVelocityHandlerObserverInterface *observer);
	
protected:

public:
	NavigationVelocityHandlerCore(
		Smart::InputSubject<CommBasicObjects::CommNavigationVelocity> *subject,
		const int &prescaleFactor=1);
	virtual ~NavigationVelocityHandlerCore();
};
#endif
