//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _SMARTSTATECHANGEHANDLERCORE_HH
#define _SMARTSTATECHANGEHANDLERCORE_HH
		
#include "aceSmartSoft.hh"

class SmartStateChangeHandlerCore : public SmartACE::StateChangeHandler
{
public:
	void handleEnterState(const std::string & substate) throw() { };
	void handleQuitState(const std::string & substate) throw() { };
};
#endif
